apiVersion: v2
name: mimir-sync
description: A Helm chart for syncing Mimir and Loki configurations including alertmanager config and rules
type: application
version: 1.3.6
appVersion: "1.0.0"

# A list of keywords as strings
keywords:
  - monitoring
  - alerting
  - prometheus
  - mimir
  - loki
  - kubernetes
  - helm

# The URL to the source code of this project
sources:
  - https://github.com/antnsn/mimir-sync

# The URL to the project's homepage
home: https://github.com/antnsn/mimir-sync

# The URL to the project's documentation
maintainers:
  - name: antnsn
    url: https://github.com/antnsn
    email: me@antnsn.dev

# The license for the project
icon: https://raw.githubusercontent.com/antnsn/mimir-sync/main/assets/logo/logo.svg

# Dependencies (if any)
dependencies: []
