# .helm-docs.yml
version: v1
chart-dir: "chart"
output-file: "README.md"
template: "chart/README.md.tpl"
sort-values: true
output-format: "yaml"
ignore:
  - "**/templates/_*.tpl"
  - "**/templates/_helpers.tpl"
  - "**/templates/NOTES.txt"
  - "**/templates/tests/*.yaml"
template-delims:
  left: "{{"
  right: "}}"
fail-on-diff: true
