{{- if .Values.alertmanager.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "mimir-sync.fullname" . }}-alertmanager-sync
  labels:
    {{- include "mimir-sync.labels" . | nindent 4 }}
    app.kubernetes.io/component: alertmanager-sync
  annotations:
    {{- if ne .Values.alertmanager.config.type "none" }}
    reloader.stakater.com/auto: "true"
    {{- if eq .Values.alertmanager.config.type "configmap" }}
    reloader.stakater.com/search: "true"
    {{- end }}
    {{- end }}
spec:
  template:
    metadata:
      labels:
        {{- include "mimir-sync.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: alertmanager-sync
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mimir-sync.serviceAccountName" . }}
      restartPolicy: OnFailure
      containers:
        - name: alertmanager-sync
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.alertmanager.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          command:
            - mal-sync
            - alertmanager
            - --config.file=/config/{{ .Values.alertmanager.config.key }}
            - --templates.dir={{ .Values.alertmanager.templatesPathInContainer }}
            - --mimir.address={{ .Values.mimir.address }}
            - --mimir.id={{ .Values.mimir.tenantId }}
            {{- if .Values.alertmanager.syncTempDir }}
            - --temp.dir={{ .Values.alertmanager.syncTempDir }}
            {{- end }}
            # MIMIR_USER and MIMIR_PASSWORD (ideally MIMIR_API_KEY) environment variables are already set for the container.
            # mal-sync's call to mimirtool will rely on mimirtool picking up these environment variables for authentication.
          {{- if ne .Values.alertmanager.config.type "none" }}
          volumeMounts:
            - name: alertmanager-config
              mountPath: /config
              readOnly: true
          {{- end }}
          {{- with .Values.alertmanager.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: MIMIR_ADDRESS
              value: "{{ .Values.mimir.address }}"
            - name: MIMIR_TENANT_ID
              value: "{{ .Values.mimir.tenantId }}"
            {{- if .Values.mimir.user }}
            - name: MIMIR_USER
              value: "{{ .Values.mimir.user }}"
            {{- end }}
            {{- if .Values.mimir.password }}
            - name: MIMIR_PASSWORD
              value: "{{ .Values.mimir.password }}"
            {{- end }}
            {{- with .Values.alertmanager.extraEnv }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
      {{- with .Values.alertmanager.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.alertmanager.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.alertmanager.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.alertmanager.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.alertmanager.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if ne .Values.alertmanager.config.type "none" }}
      volumes:
        - name: alertmanager-config
          {{- if eq .Values.alertmanager.config.type "configmap" }}
          configMap:
            name: {{ if .Values.alertmanager.config.existingName }}{{ .Values.alertmanager.config.existingName }}{{ else }}{{ include "mimir-sync.fullname" . }}-alertmanager{{ end }}
          {{- else if eq .Values.alertmanager.config.type "secret" }}
          secret:
            secretName: {{ if .Values.alertmanager.config.existingName }}{{ .Values.alertmanager.config.existingName }}{{ else }}{{ include "mimir-sync.fullname" . }}-alertmanager-config{{ end }}
          {{- end }}
      {{- end }}
      {{- with .Values.alertmanager.extraVolumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
  backoffLimit: 2
  ttlSecondsAfterFinished: 3600  # Clean up completed jobs after 1 hour
{{- end }}