{{- if and (eq .Values.alertmanager.config.type "secret") (not .Values.alertmanager.config.existingName) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mimir-sync.fullname" . }}-alertmanager-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "mimir-sync.name" . }}
    chart: {{ template "mimir-sync.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
stringData:
  {{ .Values.alertmanager.config.key }}: |
    {{- .Values.alertmanagerConfig | nindent 4 }}
{{- end -}}
