{{- if and .Values.lokiRules.enabled (eq .Values.lokiRules.config.type "configmap") (not .Values.lokiRules.config.existingName) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mimir-sync.lokiRulesConfigName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mimir-sync.labels" . | nindent 4 }}
    app.kubernetes.io/component: loki-rules-sync
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  {{- range $key, $value := .Values.lokiRules.rules }}
  {{ $key }}: |
    {{- $value | nindent 4 }}
  {{- end }}
{{- end -}}
