{{- if .Values.rules.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "mimir-sync.fullname" . }}-rules-sync
  labels:
    {{- include "mimir-sync.labels" . | nindent 4 }}
    app.kubernetes.io/component: rules-sync
  annotations:
    {{- if ne .Values.rules.config.type "none" }}
    reloader.stakater.com/auto: "true"
    {{- if eq .Values.rules.config.type "configmap" }}
    reloader.stakater.com/search: "true"
    {{- end }}
    {{- end }}
spec:
  template:
    metadata:
      labels:
        {{- include "mimir-sync.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: rules-sync
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mimir-sync.serviceAccountName" . }}
      restartPolicy: OnFailure
      containers:
        - name: rules-sync
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.rules.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          command:
            - mal-sync
            - mimir-rules
            # The rules are mounted from a ConfigMap/Secret to /rules/
            # mal-sync will process all .yaml and .yml files in this directory.
            - --rules.path=/rules/
            - --mimir.address={{ .Values.mimir.address }}
            - --mimir.id={{ .Values.mimir.tenantId }}
            # Ensure 'rules.namespace' is defined in your values.yaml or provide a default.
            # Example: - --rules.namespace={{ .Values.rules.namespace | default "default-namespace" }}
            - --rules.namespace={{ .Values.namespaces.mimir }}
            {{- if .Values.rules.syncTempDir }}
            - --temp.dir={{ .Values.rules.syncTempDir }}
            {{- end }}
            # MIMIR_USER and MIMIR_PASSWORD (ideally MIMIR_API_KEY) environment variables are already set for the container.
            # mal-sync's call to mimirtool will rely on mimirtool picking up these environment variables for authentication.
          {{- if ne .Values.rules.config.type "none" }}
          volumeMounts:
            - name: rules-config
              mountPath: /rules
              readOnly: true
          {{- end }}
          {{- with .Values.rules.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: MIMIR_ADDRESS
              value: "{{ .Values.mimir.address }}"
            - name: MIMIR_TENANT_ID
              value: "{{ .Values.mimir.tenantId }}"
            {{- if .Values.mimir.user }}
            - name: MIMIR_USER
              value: "{{ .Values.mimir.user }}"
            {{- end }}
            {{- if .Values.mimir.password }}
            - name: MIMIR_PASSWORD
              value: "{{ .Values.mimir.password }}"
            {{- end }}
            {{- with .Values.rules.extraEnv }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
      {{- with .Values.rules.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.rules.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.rules.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.rules.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.rules.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if ne .Values.rules.config.type "none" }}
      volumes:
        - name: rules-config
          {{- if eq .Values.rules.config.type "configmap" }}
          configMap:
            name: {{ if .Values.rules.config.existingName }}{{ .Values.rules.config.existingName }}{{ else }}{{ include "mimir-sync.fullname" . }}-rules{{ end }}
          {{- else if eq .Values.rules.config.type "secret" }}
          secret:
            secretName: {{ if .Values.rules.config.existingName }}{{ .Values.rules.config.existingName }}{{ else }}{{ include "mimir-sync.fullname" . }}-rules-config{{ end }}
          {{- end }}
      {{- end }}
      {{- with .Values.rules.extraVolumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
  backoffLimit: 2
  ttlSecondsAfterFinished: 3600  # Clean up completed jobs after 1 hour
{{- end }}