{{- if and (eq .Values.rules.config.type "secret") (not .Values.rules.config.existingName) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mimir-sync.fullname" . }}-rules-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "mimir-sync.name" . }}
    chart: {{ template "mimir-sync.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.prometheusRules }}
  {{ $key }}: |
    {{- $value | nindent 4 }}
  {{- end }}
{{- end -}}
