{{- if and (eq .Values.rules.config.type "configmap") (not .Values.rules.config.existingName) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mimir-sync.fullname" . }}-rules
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "mimir-sync.name" . }}
    chart: {{ template "mimir-sync.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{- range $key, $value := .Values.prometheusRules }}
  {{ $key }}: |
    {{- $value | nindent 4 }}
  {{- end }}
{{- end -}}
