groups:
  - name: node-exporter
    rules:
      - alert: NodeDown
        expr: up{job=~"k8s-nodes|external-servers"} == 0
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: Node down (instance {{ $labels.instance }})
          description: "Node is down or not responding\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: HostOutOfMemory
        expr: node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100 < 10
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: Host out of memory (instance {{ $labels.instance }})
          description: "Node memory is filling up (< 10% left)\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: HostHighCpuLoad
        expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 85
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: Host high CPU load (instance {{ $labels.instance }})
          description: "CPU load is > 85% for more than 10 minutes\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: HostOutOfDiskSpace
        expr: (node_filesystem_avail_bytes{mountpoint="/"}  / node_filesystem_size_bytes{mountpoint="/"} * 100) < 10
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: Host out of disk space (instance {{ $labels.instance }})
          description: "Disk is almost full (< 10% left)\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: HostHighLoadAverage
        expr: node_load5 > 8
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: Host high load average (instance {{ $labels.instance }})
          description: "System load average is high (5 min load > 8)\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: HighDiskIOWait
        expr: rate(node_disk_io_time_seconds_total[5m]) > 0.5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High disk I/O wait (instance {{ $labels.instance }})
          description: "Disk I/O wait is high (> 50%)\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: DiskWillFillIn24Hours
        expr: (node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"} * 100) < 15 and predict_linear(node_filesystem_avail_bytes{mountpoint="/"}[6h], 24 * 3600) < 0
        for: 30m
        labels:
          severity: critical
        annotations:
          summary: Disk will fill in 24 hours (instance {{ $labels.instance }})
          description: "Disk will fill in less than 24 hours at current write rate\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: ServiceDown
        # Check each service type separately for better alert grouping
        expr: |
          (avg_over_time(up[5m]) < 1)
          or (avg_over_time(pg_up[5m]) < 1)
          or (avg_over_time(mysql_up[5m]) < 1)
        for: 5m # Increased from 1m to prevent flapping
        labels:
          severity: critical
        annotations:
          summary: "Service {{ $labels.job }} is down"
          description: |
            {{ $labels.job }} instance {{ $labels.instance }}
            has been down for more than 5 minutes.
