name: Helm Docs

on:
  push:
    branches: [ main ]
    paths:
      - 'chart/**/*.yaml'
  pull_request:
    branches: [ main ]
    paths:
      - 'chart/**/*.yaml'
  workflow_dispatch:

jobs:
  helm-docs:
    name: Generate Helm Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run helm-docs
        uses: norwoodj/helm-docs@v1.14.2
        with:
          chart-dir: chart
          output-file: README.md
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: .helm-docs.yml

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "docs: update helm chart documentation"
          title: "docs: update helm chart documentation"
          body: "Automated update of Helm chart documentation"
          branch: "update-helm-docs"
          delete-branch: true
          base: main
          draft: false
          request-to-parent: false
          branch-suffix: timestamp
          signoff: false
          author: "GitHub Actions <actions@github.com>"
          committer: "GitHub Actions <actions@github.com>"
          add-paths: |
            chart/README.md
            .helm-docs.yml
