name: Lint and Test Chart

on:
  pull_request:
    paths:
      - 'chart/**'
      - '.github/workflows/*.yaml'

env:
  CT_BUILD_ID: "${{ github.run_id }}"
jobs:
  build:
    name: lint, install
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.17.1

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.7.0

      - name: Validate Chart Documentation
        uses: norwoodj/helm-docs@v1.11.3  # Using a specific version that's known to work
        with:
          chart-search-root: chart
          output-file: README.md
          output-dir: /tmp
          check-only: true

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed="$(ct list-changed --config chart/ct.yaml)"
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Run chart-testing (lint)
        run: ct lint  --debug --config chart/ct.yaml

      - name: Create kind cluster
        uses: helm/kind-action@a1b0e391336a6ee6713a0583f8c6240d70863de3 # v1.12.0
        if: steps.list-changed.outputs.changed == 'true'

      - name: Apply Prometheus Operator CRDs (unless for charts already installing it)
        env:
          CHANGED_LIST: ${{ steps.list-changed.outputs.changed_list }}
        run: |
          helm install prometheus-operator-crds oci://ghcr.io/prometheus-community/charts/prometheus-operator-crds
        if: steps.list-changed.outputs.changed == 'true'

      - name: Run chart-testing (install)
        run: ct install --debug --config chart/ct.yaml
        if: steps.list-changed.outputs.changed == 'true'
