name: Release Chart

# Add these permissions
permissions:
  contents: write # Needed to push to gh-pages and create PRs
  packages: write # Needed to create releases
  pull-requests: write # Needed to create pull requests

on:
  push:
    branches:
      - main
    paths:
      - "chart/**"
      - ".github/workflows/release.yaml"
  release:
    types: [created]
  workflow_dispatch:

jobs:
  release:
    name: Release Helm Chart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.17.1

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        with:
          config: .github/cr.yaml
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Helm Docs
        uses: envoy/install-helm-docs@v1.0.0
        with:
          version: 1.14.2
          
      - name: Update Chart README
        working-directory: chart
        run: |
          helm-docs
          git add README.md
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git commit -m "docs: update chart documentation" || echo "No changes to commit"
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "docs: update chart documentation"
          title: "docs: update chart documentation"
          body: "Automated update of Helm chart documentation"
          branch: "update-helm-docs"
          delete-branch: true
          base: main
