name: Release Charts

# Add these permissions
permissions:
  contents: write # Needed to push to gh-pages
  packages: write # Needed to create releases

on:
  push:
    branches:
      - main
    tags:
      - "v*" # Trigger on version tags (e.g., v1.0.0)
  workflow_dispatch: # Allow manual triggering

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.17.1

      - name: Package chart
        run: |
          mkdir -p .cr-release-packages
          helm package chart/ -d .cr-release-packages --version ${GITHUB_REF#refs/tags/}

      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create index if not exists
        run: |
          if [ ! -f gh-pages/index.yaml ]; then
            echo "apiVersion: v1" > gh-pages/index.yaml
            echo "entries: {}" >> gh-pages/index.yaml
            echo "generated: \"$(date -u +'%Y-%m-%dT%H:%M:%SZ')\"" >> gh-pages/index.yaml
          fi

      # In .github/workflows/release.yaml

      - name: Update index
        run: |
          # Copy the chart package to gh-pages
          mkdir -p gh-pages/charts
          cp .cr-release-packages/*.tgz gh-pages/charts/

          # Ensure the URL in the index is consistent
          CHART_VERSION=$(echo ${GITHUB_REF#refs/tags/v} | tr -d 'v')
          
          # Update the index with the correct URL format
          helm repo index gh-pages \
            --merge gh-pages/index.yaml \
            --url https://antnsn.github.io/mimir-sync/charts/
          
          # Fix the URLs in the index file to be consistent
          sed -i.bak 's|/mimir-sync-|/charts/mimir-sync-|g' gh-pages/index.yaml
          rm -f gh-pages/index.yaml.bak

      - name: Commit and push
        run: |
          cd gh-pages
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update Helm chart index and package"
          git push origin gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: .cr-release-packages/*.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
