name: Release Chart

# Add these permissions
permissions:
  contents: write # Needed to push to gh-pages
  packages: write # Needed to create releases

on:
  push:
    branches:
      - main
    paths:
      - "chart/**"
      - ".github/workflows/release.yaml"
  release:
    types: [created]
  workflow_dispatch:

jobs:
  release:
    name: Release Helm Chart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.17.1

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        with:
          config: .github/cr.yaml
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Chart README
        uses: jkroepke/helm-docs-action@v1.14.2
        with:
          chart-dir: chart
          output-file: README.md
