name: Release Charts

# Add these permissions
permissions:
  contents: write # Needed to push to gh-pages
  packages: write # Needed to create releases

on:
  push:
    branches:
      - main
    tags:
      - "v*" # Trigger on version tags (e.g., v1.0.0)
  workflow_dispatch: # Allow manual triggering

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.17.1

      - name: Generate Helm Docs
        uses: norwoodj/helm-docs-action@v1.9.0
        with:
          chart-dir: chart
          output-file: README.md

      - name: Package chart
        run: |
          mkdir -p .cr-release-packages
          # Remove 'v' from version in filename
          VERSION=${GITHUB_REF#refs/tags/v}
          helm package chart/ -d .cr-release-packages --version ${VERSION}
          # Rename the file to remove 'v' from the filename
          mv .cr-release-packages/mimir-sync-v${VERSION}.tgz .cr-release-packages/mimir-sync-${VERSION}.tgz || true

      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create index if not exists
        run: |
          if [ ! -f gh-pages/index.yaml ]; then
            echo "apiVersion: v1" > gh-pages/index.yaml
            echo "entries: {}" >> gh-pages/index.yaml
            echo "generated: \"$(date -u +'%Y-%m-%dT%H:%M:%SZ')\"" >> gh-pages/index.yaml
          fi

      # In .github/workflows/release.yaml

      - name: Update index
        run: |
          # Copy the chart package to the root of gh-pages
          mkdir -p gh-pages/charts
          cp .cr-release-packages/*.tgz gh-pages/charts/
          
          # Get the version without 'v' prefix
          VERSION=${GITHUB_REF#refs/tags/v}
          
          # Create a clean index in a temporary location
          mkdir -p temp-index
          cp gh-pages/charts/*.tgz temp-index/
          
          # Generate the index with the correct base URL
          helm repo index temp-index --url https://antnsn.github.io/mimir-sync/charts/
          
          # Merge with existing index if it exists
          if [ -f gh-pages/index.yaml ]; then
            helm repo index temp-index --merge gh-pages/index.yaml --url https://antnsn.github.io/mimir-sync/charts/
          fi
          
          # Copy the new index to gh-pages
          cp temp-index/index.yaml gh-pages/
          
          # Clean up
          rm -rf temp-index

      - name: Commit and push
        run: |
          cd gh-pages
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update Helm chart index and package"
          git push origin gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: .cr-release-packages/*.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
